# settings.py

"""
Django settings for security_api project.

Generated by 'django-admin startproject' using Django 4.2.20.
(Comentario original del usuario, la versión de Django podría ser 5.x según otro log)

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/ (o la versión correspondiente)

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/ (o la versión correspondiente)
"""

from pathlib import Path
import os # Importar os para getenv si decides usarlo para otras cosas

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Intenta cargarla desde variables de entorno para mayor seguridad,
# pero si no, usa la que Django generó para desarrollo.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-b&f0a=ail6cefv&u25$otycd&1^@7(-=1wf_u)y9c6cq+rox%m')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True' # Lee DEBUG desde .env o usa True por defecto

# Hosts permitidos para servir la aplicación Django
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # Añade el host de producción cuando despliegues, ej: 'miapi.ejemplo.com'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps de Terceros
    'rest_framework',
    'corsheaders',      # Para manejar Cross-Origin Resource Sharing

    # Tus Apps
    'api',              # Tu app 'api'
    'core',             # Tu app 'core'
    'chat',             # Tu app 'chat'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Debe ir antes de CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # Considera cómo manejarás CSRF con APIs y SPA
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'security_api.urls' # Asegúrate que coincida con el nombre de tu carpeta de proyecto que contiene este settings.py y el urls.py principal

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Buena práctica añadir un dir de templates a nivel de proyecto
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'security_api.wsgi.application' # Ajusta 'security_api' si el nombre de tu carpeta de proyecto es otro


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Configuración de base de datos por defecto (SQLite).
# Si usas PostgreSQL con Docker Compose como indicaba tu .env,
# deberías configurar eso aquí, usando python-dotenv para cargar DATABASE_URL
# Ejemplo con DATABASE_URL (requiere instalar dj-database-url: pip install dj-database-url)
# import dj_database_url
# from dotenv import load_dotenv
# load_dotenv() # Cargar .env

# DATABASE_URL_FROM_ENV = os.getenv('DATABASE_URL')
# if DATABASE_URL_FROM_ENV:
#     DATABASES = {
#         'default': dj_database_url.parse(DATABASE_URL_FROM_ENV, conn_max_age=600)
#     }
# else:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-cl' # Cambiado a español de Chile como ejemplo
TIME_ZONE = 'America/Santiago' # Cambiado a zona horaria de Chile como ejemplo

USE_I18N = True
USE_TZ = True # Recomendado mantenerlo True para manejo de zonas horarias


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/' # El slash al final es importante
# Opcional: Para servir archivos estáticos en desarrollo desde un directorio a nivel de proyecto
# STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Configuración de CORS ---
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",  # Origen de tu frontend Angular en desarrollo
    "http://127.0.0.1:4200", # Alternativa para localhost
]

# Si en algún momento necesitas permitir todas las fuentes para pruebas rápidas (NO para producción):
# CORS_ALLOW_ALL_ORIGINS = True

# Si tu frontend necesita enviar credenciales (como cookies o cabeceras de autenticación)
# CORS_ALLOW_CREDENTIALS = True

# Configuración de Django REST Framework (opcional, pero común si usas DRF)
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         # 'rest_framework.authentication.SessionAuthentication', # Si usas login de Django
#         # 'rest_framework.authentication.TokenAuthentication', # Si usas Tokens DRF
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticatedOrReadOnly', # Ejemplo
#     ),
# }

# Configuración de Logging (ejemplo básico, puedes expandirlo)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO', # Puedes cambiar a DEBUG para más detalle
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}